# Site settings
title: Li Weinan
email: liweinan0423@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personl blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "liweinan0423.github.io" # the base hostname & protocol for your site
twitter_username: liweinan0423
github_username:  liweinan0423

# Build settings
markdown: kramdown
